name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: standard-runner-no-rights-public-ip
    permissions:
      packages: write
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Test Aikido Upload Code Coverage action in workflow with OIDC
        uses: ./
        with:
          lcov-file-paths: coverage/lcov.info
        env:
          ACTIONS_STEP_DEBUG: 'true'
