name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: open-source-releaser
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  upload-coverage:
    runs-on: open-source-releaser
    needs: build-and-test
    if: github.event_name == 'push'
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Test Aikido Upload Code Coverage action in workflow with OIDC
        uses: ./
        with:
          lcov-file-paths: coverage/lcov.info
        env:
          ACTIONS_STEP_DEBUG: 'true'
